### PR TITLE
Fix win32  build

### PR DESCRIPTION
**Pull request by roojs**
ref  https://wiki.php.net/internals/windows/stepbystepbuild_sdk_2

fix by Andrzej Wiśniewski

### CODE REVIEW

**Comment by cmb69** [comment]
Hmm, I think it's better to leave this as is. If one really does an in-tree build (i.e. copying the extension to PHP's ext/ folder), they actually might want to have the extension built-in; if they want to build it shared, they can still pass the `--with-all-shared` configure option. And if they're doing a phize build (what I would recommend), the extension is built as DLL anyway.

Or do I miss something?

**Comment by roojs** [comment]
No idea personally - don't use win32 - just sent that patch by Andrzej - might be better to have someone with win32 knowledge comment on it

**Comment by cmb69** [comment]
Some clarifications and corrections: there are three ways of building an extension on Windows:

1. real "in-tree builds" (i.e. dropping the extension in the ext/ folder)
2. ["pecl-tree" builds](https://wiki.php.net/internals/windows/stepbystepbuild_sdk_2#building_pecl_extensions)
3. [phpize builds](https://wiki.php.net/internals/windows/stepbystepbuild_sdk_2#building_pecl_extensions_with_phpize)

(3) always builds shared extensions; (1) and (2) default to static, but with the suggested change the default would be shared. If you want a shared build with the current config.w32, you can `configure --with-all-shared`, or just `configure --enable-dbase=shared`. After the change it would no longer be possible to do static builds (if I'm not seriously mistaken).

I don't really mind about this change, since I almost always do phpize builds for a long time, and there you always get a dynamic library. This build style is also used by the [Windows CI](https://github.com/php/pecl-database-dbase/blob/master/.github/workflows/ci.yml), and also for the [PECL builds](https://github.com/php/php-windows-builder) now. Only https://github.com/php/web-rmtools (which was used on the now defunct PECL build machine) does "pecl-tree" builds, but obviously forces the extensions to be built as shared libraries (but [that repo might be archived](https://github.com/php/web-rmtools/issues/22) soon, anyway).

So, the change would only affect the (few) users who roll their own builds, and changing the behavior might be undesireable for them.

@roojs, maybe you can reach out to Andrzej Wiśniewski and ask whether `configue --enable-dbase=shared` would solve the issue for him (without any changes to config.w32).

**Comment by Jan-E** [comment]
I am doing real "in-tree builds" with a `--enable-snapshot-build`. As long as the thirf argument in the ARG_ENABLE line is 'no' the snapshot build will compile an extensions as shared. If the third argument is 'yes' I have to explicitely add --enable-ext=shared to the configure line. For instance:
`
ARG_ENABLE("com-dotnet", "COM and .Net support", "yes");
`
requires an explicit
`
--enable-com-dotnet=shared
`
to build it as shared php_com_dotnet.dll

**Comment by Jan-E** [comment]
BTW, the configure line for the PHP 8.4.0 builds on windows.php.net is

`cscript /nologo /e:jscript configure.js "--enable-snapshot-build" "--enable-debug-pack" "--disable-zts" "--enable-object-out-dir=../obj/" "--enable-com-dotnet=shared" "--without-analyzer" "--with-pgo"
`

The `--enable-com-dotnet=shared` is only needed because the third argument in `ARG_ENABLE("com-dotnet", "COM and .Net support", "yes")` still is 'yes'.

**Comment by cmb69** [comment]
> The `--enable-com-dotnet=shared` is only needed because the third argument in `ARG_ENABLE("com-dotnet", "COM and .Net support", "yes")` still is 'yes'.

That's likely a relict from the olden times where that extension has been built statically for the official binaries, and when that changed, probably config.w32 hasn't changed deliberately, to not break the work flows of users rolling their own builds. I think that it's something we might want to change, but that should be discussed elsewhere (either https://github.com/php/php-src/issues, or internals/internals-win mailing lists).

Anyhow, I'm closing this ticket. If someone comes up with an explanation why the default should be changed, we can still re-open.

**Pull request closed without merging**
