### PR TITLE
Add tests for Ubuntu 32bit

### PR DESCRIPTION
**Pull request by MauricioFauth**
https://github.com/shivammathur/setup-php#multi-arch-setup

### CODE REVIEW

**Comment by cmb69** [comment]
I'm not sure whether it makes sense to add CI for 32bit platforms. As I understand it, even the core PHP developers don't have strong interest in keeping x86 support alive.

**Comment by MauricioFauth** [comment]
I agree, but 32bit is still supported and it doesn't adds much to the CI.

**Comment by cmb69** [comment]
Okay, given the likely few CI runs this repo has, adding some 32bit CI is not a problem. Would you please resolve the merge conflicts (I think the action update already happened, and also switching to php/setup-php-action).

**Comment by MauricioFauth** [comment]
> Okay, given the likely few CI runs this repo has, adding some 32bit CI is not a problem. Would you please resolve the merge conflicts (I think the action update already happened, and also switching to php/setup-php-action).

@cmb69 Done!

**Comment by cmb69** [comment]
Thank you!

**Pull request merged**
