### PR TITLE
Convert dbase resource to object

### PR DESCRIPTION
**Pull request by MauricioFauth**
Converts the resource of type `dbase` into the `Dbase\DbaseHandle` object.

### CODE REVIEW

**Comment by MauricioFauth** [comment]
Hi @cmb69, I think this is ready for review now. Thank you.

**Comment by cmb69** [comment]
Thank you for the PR! I would stick with resources for BC reasons as long as possible, though (unless someone is planning to actually develop this extension further), and I don't think that PHP will drop support for resources anytime soon.

**Comment by MauricioFauth** [comment]
> Thank you for the PR! I would stick with resources for BC reasons as long as possible, though (unless someone is planning to actually develop this extension further), and I don't think that PHP will drop support for resources anytime soon.

@cmb69 Makes sense. So, maybe is better to develop an OOP API and leave the functions as is, and, if PHP drops support for resources, deprecate the functional API or convert it to object when that happens.

**Comment by cmb69** [comment]
Frankly, I think it might be best to develop an alternative to ext/dbase in PHP. The performance difference shouldn't matter that much (maybe a couple of utility functions could still be supplied in C), but maintainance would be much easier.

**Pull request closed without merging**
